export const typeNameKo: Record<string, string> = {
  fire: "불",
  water: "물",
  grass: "풀",
  electric: "전기",
  psychic: "에스퍼",
  dragon: "드래곤",
  normal: "노말",
  fighting: "격투",
  flying: "비행",
  poison: "독",
  ground: "땅",
  rock: "바위",
  bug: "벌레",
  ghost: "고스트",
  ice: "얼음",
  dark: "악",
  steel: "강철",
  fairy: "페어리",
};
